/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EggsRouteImport } from './routes/eggs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerServerIdRouteImport } from './routes/server/$serverId'
import { Route as AdminCreateServerRouteImport } from './routes/admin/create-server'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminNodesIndexRouteImport } from './routes/admin/nodes/index'
import { Route as AdminEggsIndexRouteImport } from './routes/admin/eggs/index'
import { Route as AdminNodesNodeIdRouteImport } from './routes/admin/nodes/$nodeId'
import { Route as AdminEggsCreateRouteImport } from './routes/admin/eggs/create'
import { Route as AdminEggsEggIdRouteImport } from './routes/admin/eggs/$eggId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EggsRoute = EggsRouteImport.update({
  id: '/eggs',
  path: '/eggs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateServerRoute = AdminCreateServerRouteImport.update({
  id: '/admin/create-server',
  path: '/admin/create-server',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/admin/nodes/',
  path: '/admin/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEggsIndexRoute = AdminEggsIndexRouteImport.update({
  id: '/admin/eggs/',
  path: '/admin/eggs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNodesNodeIdRoute = AdminNodesNodeIdRouteImport.update({
  id: '/admin/nodes/$nodeId',
  path: '/admin/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEggsCreateRoute = AdminEggsCreateRouteImport.update({
  id: '/admin/eggs/create',
  path: '/admin/eggs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEggsEggIdRoute = AdminEggsEggIdRouteImport.update({
  id: '/admin/eggs/$eggId',
  path: '/admin/eggs/$eggId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eggs': typeof EggsRoute
  '/login': typeof LoginRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/eggs/$eggId': typeof AdminEggsEggIdRoute
  '/admin/eggs/create': typeof AdminEggsCreateRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/eggs/': typeof AdminEggsIndexRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eggs': typeof EggsRoute
  '/login': typeof LoginRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/eggs/$eggId': typeof AdminEggsEggIdRoute
  '/admin/eggs/create': typeof AdminEggsCreateRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/eggs': typeof AdminEggsIndexRoute
  '/admin/nodes': typeof AdminNodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eggs': typeof EggsRoute
  '/login': typeof LoginRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/eggs/$eggId': typeof AdminEggsEggIdRoute
  '/admin/eggs/create': typeof AdminEggsCreateRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/eggs/': typeof AdminEggsIndexRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eggs'
    | '/login'
    | '/admin/activity'
    | '/admin/create-server'
    | '/server/$serverId'
    | '/admin/eggs/$eggId'
    | '/admin/eggs/create'
    | '/admin/nodes/$nodeId'
    | '/admin/eggs/'
    | '/admin/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eggs'
    | '/login'
    | '/admin/activity'
    | '/admin/create-server'
    | '/server/$serverId'
    | '/admin/eggs/$eggId'
    | '/admin/eggs/create'
    | '/admin/nodes/$nodeId'
    | '/admin/eggs'
    | '/admin/nodes'
  id:
    | '__root__'
    | '/'
    | '/eggs'
    | '/login'
    | '/admin/activity'
    | '/admin/create-server'
    | '/server/$serverId'
    | '/admin/eggs/$eggId'
    | '/admin/eggs/create'
    | '/admin/nodes/$nodeId'
    | '/admin/eggs/'
    | '/admin/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EggsRoute: typeof EggsRoute
  LoginRoute: typeof LoginRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCreateServerRoute: typeof AdminCreateServerRoute
  ServerServerIdRoute: typeof ServerServerIdRoute
  AdminEggsEggIdRoute: typeof AdminEggsEggIdRoute
  AdminEggsCreateRoute: typeof AdminEggsCreateRoute
  AdminNodesNodeIdRoute: typeof AdminNodesNodeIdRoute
  AdminEggsIndexRoute: typeof AdminEggsIndexRoute
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eggs': {
      id: '/eggs'
      path: '/eggs'
      fullPath: '/eggs'
      preLoaderRoute: typeof EggsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-server': {
      id: '/admin/create-server'
      path: '/admin/create-server'
      fullPath: '/admin/create-server'
      preLoaderRoute: typeof AdminCreateServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nodes/': {
      id: '/admin/nodes/'
      path: '/admin/nodes'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eggs/': {
      id: '/admin/eggs/'
      path: '/admin/eggs'
      fullPath: '/admin/eggs/'
      preLoaderRoute: typeof AdminEggsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nodes/$nodeId': {
      id: '/admin/nodes/$nodeId'
      path: '/admin/nodes/$nodeId'
      fullPath: '/admin/nodes/$nodeId'
      preLoaderRoute: typeof AdminNodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eggs/create': {
      id: '/admin/eggs/create'
      path: '/admin/eggs/create'
      fullPath: '/admin/eggs/create'
      preLoaderRoute: typeof AdminEggsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eggs/$eggId': {
      id: '/admin/eggs/$eggId'
      path: '/admin/eggs/$eggId'
      fullPath: '/admin/eggs/$eggId'
      preLoaderRoute: typeof AdminEggsEggIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EggsRoute: EggsRoute,
  LoginRoute: LoginRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminCreateServerRoute: AdminCreateServerRoute,
  ServerServerIdRoute: ServerServerIdRoute,
  AdminEggsEggIdRoute: AdminEggsEggIdRoute,
  AdminEggsCreateRoute: AdminEggsCreateRoute,
  AdminNodesNodeIdRoute: AdminNodesNodeIdRoute,
  AdminEggsIndexRoute: AdminEggsIndexRoute,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
