/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerServerIdRouteImport } from './routes/server/$serverId'
import { Route as AdminEggsRouteImport } from './routes/admin/eggs'
import { Route as AdminCreateServerRouteImport } from './routes/admin/create-server'
import { Route as AdminNodesIndexRouteImport } from './routes/admin/nodes/index'
import { Route as AdminNodesNodeIdRouteImport } from './routes/admin/nodes/$nodeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEggsRoute = AdminEggsRouteImport.update({
  id: '/admin/eggs',
  path: '/admin/eggs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateServerRoute = AdminCreateServerRouteImport.update({
  id: '/admin/create-server',
  path: '/admin/create-server',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/admin/nodes/',
  path: '/admin/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNodesNodeIdRoute = AdminNodesNodeIdRouteImport.update({
  id: '/admin/nodes/$nodeId',
  path: '/admin/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/nodes': typeof AdminNodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/create-server': typeof AdminCreateServerRoute
  '/admin/eggs': typeof AdminEggsRoute
  '/server/$serverId': typeof ServerServerIdRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/create-server'
    | '/admin/eggs'
    | '/server/$serverId'
    | '/admin/nodes/$nodeId'
    | '/admin/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/create-server'
    | '/admin/eggs'
    | '/server/$serverId'
    | '/admin/nodes/$nodeId'
    | '/admin/nodes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/create-server'
    | '/admin/eggs'
    | '/server/$serverId'
    | '/admin/nodes/$nodeId'
    | '/admin/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCreateServerRoute: typeof AdminCreateServerRoute
  AdminEggsRoute: typeof AdminEggsRoute
  ServerServerIdRoute: typeof ServerServerIdRoute
  AdminNodesNodeIdRoute: typeof AdminNodesNodeIdRoute
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eggs': {
      id: '/admin/eggs'
      path: '/admin/eggs'
      fullPath: '/admin/eggs'
      preLoaderRoute: typeof AdminEggsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-server': {
      id: '/admin/create-server'
      path: '/admin/create-server'
      fullPath: '/admin/create-server'
      preLoaderRoute: typeof AdminCreateServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nodes/': {
      id: '/admin/nodes/'
      path: '/admin/nodes'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nodes/$nodeId': {
      id: '/admin/nodes/$nodeId'
      path: '/admin/nodes/$nodeId'
      fullPath: '/admin/nodes/$nodeId'
      preLoaderRoute: typeof AdminNodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCreateServerRoute: AdminCreateServerRoute,
  AdminEggsRoute: AdminEggsRoute,
  ServerServerIdRoute: ServerServerIdRoute,
  AdminNodesNodeIdRoute: AdminNodesNodeIdRoute,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
